version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
